# Generated by Django 2.2.12 on 2021-08-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='jugadores_C',
        ),
        migrations.RemoveField(
            model_name='group',
            name='jugadores_SC',
        ),
        migrations.RemoveField(
            model_name='group',
            name='pago_promedio_C',
        ),
        migrations.RemoveField(
            model_name='group',
            name='pago_promedio_SC',
        ),
        migrations.RemoveField(
            model_name='group',
            name='total_performance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='belief',
        ),
        migrations.RemoveField(
            model_name='player',
            name='c_1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='c_2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='player',
            name='consent_account',
        ),
        migrations.RemoveField(
            model_name='player',
            name='filtro',
        ),
        migrations.RemoveField(
            model_name='player',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='player',
            name='market',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='palabras',
        ),
        migrations.RemoveField(
            model_name='player',
            name='task_pay',
        ),
    ]
