# Generated by Django 2.2.12 on 2021-08-14 22:31

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_player_aditional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aditional',
        ),
        migrations.AddField(
            model_name='player',
            name='win_belief',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
