# Generated by Django 2.2.12 on 2021-08-15 00:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20210814_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='identificador',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Para iniciar por favor ingrese las iniciales de su primer nombre y apellido seguido de su fecha de nacimiento. Por ejemplo, si usted se llama Lina Ríos y usted nació el 11 de febrero de 1995, debe ingresar LR11021995. Escriba todo en mayúscula. Esta etiqueta es importante para asegurar su participación en el resto de la actividad y la realización de los pagos.'),
        ),
    ]
